In [32]:
import math
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error


In [33]:
x = np.array([1,2,3,4,5])
y = np.array([20,40,50,65,80])
print(x,y)

[1 2 3 4 5] [20 40 50 65 80]


In [34]:
x_mean = x.mean()
y_mean = y.mean()
print(x_mean,y_mean)

3.0 51.0


In [35]:
#design matrix
xm = np.array([[1, x_i, x_i**2] for x_i in x])
print(xm)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


In [36]:
x_transpose = xm.T
x_transpose_x = np.dot(x_transpose, xm)
print(x_transpose)
print()
print(x_transpose_x)

[[ 1  1  1  1  1]
 [ 1  2  3  4  5]
 [ 1  4  9 16 25]]

[[  5  15  55]
 [ 15  55 225]
 [ 55 225 979]]


In [37]:
x_transpose_y = np.dot(x_transpose,y)
print(x_transpose_y)

[ 255  910 3670]


In [38]:
x_transpose_x_inv = np.linalg.inv(x_transpose_x)
print(x_transpose_x_inv)

[[ 4.6        -3.3         0.5       ]
 [-3.3         2.67142857 -0.42857143]
 [ 0.5        -0.42857143  0.07142857]]


In [39]:
theeta = np.dot(x_transpose_x_inv, x_transpose_y)
print(theeta)

[ 5.         16.64285714 -0.35714286]


In [40]:
#print euqation
print(f"y = {theeta[0]} + {theeta[1]}*)x+{theeta[2]}*x^2")


y = 5.000000000000309 + 16.642857142857036*)x+-0.357142857142843*x^2


In [41]:
#residual error calculation
y_pred = np.dot(xm, theeta)
residuals = y - y_pred
print(residuals)

[-1.28571429  3.14285714 -1.71428571 -0.85714286  0.71428571]


In [45]:
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = math.sqrt(mse)
r2 = r2_score(y, y_pred)
mape = mean_absolute_percentage_error(y, y_pred)
mspe = np.mean((residuals / y) ** 2)
rmspe = np.sqrt(mspe)


In [46]:
print("MSE:", mse)
print("RMSE:", rmse)
print("MAE:", mae)
print("R2:", r2)
print("MAPE:", mape)
print("MSPE:", mspe)
print("RMSPE:", rmspe)

MSE: 3.142857142857151
RMSE: 1.772810520855839
MAE: 1.5428571428571765
R2: 0.9925876010781671
MAPE: 0.03985164835165027
MSPE: 0.002347048816568245
RMSPE: 0.04844634987868792
